org.gradle.jvmargs=-Xmx1536M
kotlin.jvm.target.validation.mode=warning
android.useAndroidX=true
android.enableJetifier=true

RELEASE_STORE_PASSWORD=flamingo123$
RELEASE_KEY_PASSWORD=flamingo123$
RELEASE_KEY_ALIAS=key0
# RELEASE_STORE_FILE=D:\\Projects\\flamingo-main\\flamingo-mobile\\android\\upload-keystore.jks
# RELEASE_STORE_FILE=/Users/rojanthapa/Desktop/Flamingo/flamingo-mobile/android/upload-keystore.jks
RELEASE_STORE_FILE=/Users/pragyan/Desktop/Projects/flamingo/flamingo-mobile/android/upload-keystore.jks

MAPS_API_KEY=AIzaSyDNj4Zb6htfMVl26pxo55bUGKZ4nMMZRNU
